### ISSUE TITLE
Usage for entire page

### ISSUE THREAD

**Issue by bradisbell** [riot/ssr#10]
What is the suggested way to render out an entire page?

For example, in my normal Riot.js applications, I have something like this:

## index.html
```html
<!doctype html>
<html>
  <head>...</head>
  <body>
    <my-riot-component></my-riot-component>
  </body>
</html>
```

It's my understanding that we cannot have a Riot.js component at the root of the document, so it seems that it must be nested in some outer HTML.  If that's the case, then does the server-side rendering package have a recommended way to incorporate the rendered components back into the outer page?

**Comment by GianlucaGuarini** [comment]
This feature was added in the new major release https://github.com/riot/ssr#advanced-tips
