### ISSUE TITLE
How to render all related components ?

### ISSUE THREAD

**Issue by rzfang** [riot/ssr#11]
I have tag1.riot to use tag2.riot, and call ssr.fragments() for tag1.
It only handles tag1 and keep tag2 as a empty tag...

here is a sample to show my issue:
https://codesandbox.io/s/xenodochial-leaf-8jflb

**Comment by cybervaldez** [comment]
Hi tag1 should export a components property with tag2 in it
export default { components : { tag2 } }

here's how I do mine including getting all the css from the children components.
https://codesandbox.io/s/kind-bhaskara-g5tqh?fontsize=14&hidenavigation=1&theme=dark

**Comment by GianlucaGuarini** [comment]
@cybervaldez thank you. That's right @rzfang forgot to import the Riot.js component into tag1

**Comment by rzfang** [comment]
Sorry, didn't catch this, is this in the document ?
Thanks you both, @cybervaldez , @GianlucaGuarini
