### ISSUE TITLE
Need example!

### ISSUE THREAD

**Issue by xeroxstar** [riot/ssr#15]
Is there an example how to do it with `require `rather `import`? 

```
import MyComponent from './my-component.riot'
import render from '@riotjs/ssr'

const html = render('my-component', MyComponent, { some: 'initial props' })
```

this one will not work but i cant use `import `:

```
const html = require('@riotjs/ssr').render('my-component', require('./my-component.riot'), { some: 'initial props' })
```

Thanks

**Comment by GianlucaGuarini** [comment]
With common js you will need to target the `.default` export
```js
const render = require('@riotjs/ssr').default
const MyComponent = require('./my-component').default

const html = render('my-component', MyComponent, { some: 'initial props' })
```

**Comment by xeroxstar** [comment]
> ```js
> const render = require('@riotjs/ssr').default
> const MyComponent = require('./my-component').default
> 
> const html = render('my-component', MyComponent, { some: 'initial props' })
> ```

It wont work either, it throw an error:

```
<my-component>
^

SyntaxError: Unexpected token '<'
```

and here is my component code: 
```
<my-component>
<script> export default{}</script>
<my-component>
```

Never mind, as i guess, i have to use a webpack to make it work! Thanks

**Comment by xeroxstar** [comment]
> With common js you will need to target the `.default` export
> 
> ```js
> const render = require('@riotjs/ssr').default
> const MyComponent = require('./my-component').default
> 
> const html = render('my-component', MyComponent, { some: 'initial props' })
> ```

I guess i had only to require the '@riotjs/ssr/register' module, here is an example how i solved it :

```
require('@riotjs/ssr/register')({ exts: ['.riot', '.av'] })

const render      = require('@riotjs/ssr').default
const MyComponent = require('../examples/Basic/www/tag.av').default;

const html = render('tag', MyComponent, { some: 'initial props' })

console.log(html)
```

**Comment by markgarrigan** [comment]
I can't get past this error...

Cannot find module '@babel/preset-env'

when doing this...

require('@riotjs/ssr/register')({ exts: ['.riot'] })
const render = require('@riotjs/ssr').default
const heading = require('heading.riot').default
