### ISSUE TITLE
Cannot render child components

### ISSUE THREAD

**Issue by damusix** [riot/ssr#17]
If you can take a look at this file and tell me what I'm doing wrong. 
I'm console logging the output and nested components are not being rendered. 
I looked at tests in riot/ssr to get some ideas but I can't spot anything that sticks out that's totally different. https://github.com/damusix/hapi-riot/blob/alpha/errortest.js

**Comment by GianlucaGuarini** [comment]
You don't load your nested components nor register them globally. Please read the [documetation](https://riot.js.org/documentation/#nested-components)
