### ISSUE TITLE
Deno?

### ISSUE THREAD

**Issue by HerrHase** [riot/ssr#26]
I'm check for a way to use Deno in a project and also Riot, ever tried Deno with ssr?

**Comment by GianlucaGuarini** [comment]
I don't think it is possible yet. [basicHTML](https://github.com/WebReflection/basicHTML) seems to be not compatible with it. 
It will be possible in the near future though ;)

**Comment by HerrHase** [comment]
Thanks for the quick answer. I suspected that, but if it works in the near future that would be great :)
