### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by rudinandrey** [riot/ssr#31]
Hello, on this page error:
https://riot.js.org/documentation/#server-side-rendering

in this example:
```
const render = require('@riotjs/ssr')
const Timer = require('timer.riot')
const html = render('timer', Timer, { start: 42 })
console.log(html) // <timer><p>Seconds Elapsed: 42</p></timer>
```

I got that error:
```
const html = render('hello', Hello, {name: 'Andrey'});
             ^
TypeError: render is not a function
```

`const html = render.render('timer', Timer, { start: 42 })`

works perfectly

**Comment by GianlucaGuarini** [comment]
thank you for the issue. Could you please open a PR https://github.com/riot/riot.github.io ?
