### ISSUE TITLE
How to import `.riot` components using node with ESM

### ISSUE THREAD

**Issue by mj026** [riot/ssr#33]
Hi!

I was trying to do something similar as stated in the README to make the import of `.riot` components work with NodeJS:
```javascript
import register from '@riotjs/ssr/register.js'

register()

import Random from "./src/js/components/random.riot"
console.log(Random)
```
When I run this with node, it will fail:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".riot" for /Users/martijn/Dev/private/riot-playground/src/js/components/random.riot
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:75:21)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:80:9) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
```

When I rewrite it to CJS instead of ESM:
```javascript
const register = require('@riotjs/ssr/register')

register()

const Random = require('./src/js/components/random.riot').default

console.log(Random)
```
it works as expected:
```
{
  css: null,
  exports: {
    components: { Logs: [Object] },
    state: { number: null, logs: [] },
    generate: [Function: generate],
    clearLogs: [Function: clearLogs]
  },
  template: [Function: template],
  name: 'random'
}
```

When I look at the [register source code](https://github.com/riot/ssr/blob/main/src/register.js), it adds a hook with the pirates module for compiling the component to javascript on the fly. Is it that this mechanism doesn't work for ESM modules?

Do I need to do something else to make this work? I would like to use the SSR feature to unittest the components with Mocha. Example repo: https://github.com/maerteijn/riot-playground

Thank you for your time.

**Comment by geonanorch** [comment]
@maerteijn I just stumbled over this problem so I am of course wondering why you closed your own issue 😉. Were you able to solve it ?
@GianlucaGuarini  of course any hint from your end would also be very welcome! A node version issue is all I can think of.

**Comment by GianlucaGuarini** [comment]
@geonanorch that's not a riot issue. If you want to use esm with node you might use [`babel-node`](https://babeljs.io/docs/en/babel-node), [esm](https://www.npmjs.com/package/esm) or anything that supports the module syntax. 

For all the other cases you might prefer compiling your tags before importing them via node

**Comment by mj026** [comment]
@geonanorch Hi, I closed it because I couldn’t get this to work with ESM imports and moved on (and didn’t want to leave it open for the maintainer when I’m not using it)

**Comment by geonanorch** [comment]
Thank you both for replying so quickly, appreciated.
**esm** looks promising, thank you @GianlucaGuarini for the tip. My undertanding is that the code shown in the section _"register - to load riot components in node_" in **riot/ssr/README.md** does not work, or is at least deceiving (requires a specific context ?). I don't feel knowledgeable enough to submit a PR, however.
I just started exploring the topic, but it looks like the road to SSR is a challenging one, next to riot I also have to sort out web components...  @maerteijn if you became wiser on that topic don't hesitate to comment or PM me 🙂

**Comment by GianlucaGuarini** [comment]
> but it looks like the road to SSR is a challenging one,

I can't do more than writing documentation and add a simple example for it https://github.com/riot/examples/tree/gh-pages/ssr

Feel free to use whatever works better for you and your team

**Comment by geonanorch** [comment]
Please don't take me wrong, you have always been helpful @GianlucaGuarini and I love what you do and bring with Riot.js. This was more of a rambling about the state of web technology in general.
