### ISSUE TITLE
Slots do not render as aspected (using Webpack Project Template)

### ISSUE THREAD

**Issue by bluellyr** [riot/ssr#36]
### Environment

macOS Monterey 12.3.1
node@17.8.0
npm@8.7.0

Tested using: chrome@100.0.4896.127

### Project init
"npm init riot" => Webpack Project Template

### package.json

```json
{
    "name": "riot-webpack",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "nyc --require esm --require jsdom-global/register --require @riotjs/register mocha src/**/*.spec.js",
        "cov": "nyc report --reporter=text-lcov",
        "cov-html": "nyc report --reporter=html",
        "build": "webpack --mode production",
        "prepublishOnly": "npm test",
        "start": "webpack serve --mode development --hot --port 3000"
    },
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@riotjs/compiler": "^6.0.1",
        "@riotjs/register": "^5.0.0",
        "@riotjs/webpack-loader": "^6.0.0",
        "chai": "^4.3.4",
        "css-loader": "^6.2.0",
        "esm": "^3.2.25",
        "html-webpack-plugin": "^5.3.2",
        "jsdom": "^16.6.0",
        "jsdom-global": "^3.0.2",
        "mini-css-extract-plugin": "^2.1.0",
        "mocha": "^8.4.0",
        "nyc": "^15.1.0",
        "webpack": "^5.47.1",
        "webpack-cli": "^4.7.2",
        "webpack-dev-server": "^3.11.2"
    },
    "dependencies": {
        "@riotjs/hot-reload": "^6.0.0",
        "@riotjs/lazy": "^2.0.1",
        "@riotjs/route": "^8.0.0",
        "riot": "^6.0.2"
    }
}
```

### Issue
I am trying to test the usage of ```slots``` and ```named slots``` following the examples on the Riot documentation:
- https://riot.js.org/api/#slots
- https://riot.js.org/api/#named-slots

but the example of a ```slot``` or ```named slot``` does not render the html as on the documentation.

### ```slot``` example

my-post.riot
```html
<my-post>
  <h1>{ props.title }</h1>
  <p><slot/></p>
</my-post>
```

index.html
```html
...
<div is="my-post" data-riot-component title="What a great title">
    My beautiful post is <b>just awesome</b>
</div>
...
```

the html is rendered as:
```html
<div is="my-post" data-riot-component="" title="What a great title">
    My beautiful post is <b>just awesome</b>
    <h1>What a great title</h1>
    <p></p>
</div>
```

and not as it is on the documentation:
```html
<my-post>
  <h1>What a great title</h1>
  <p>My beautiful post is <b>just awesome</b></p>
</my-post>
```

### ```named slot``` example

The same happens with the ```named slot```:

my-other-post.riot
```html
<my-other-post>
  <article>
    <h1>{ props.title }</h1>
    <h2><slot name="summary"/></h2>
    <article>
      <slot name="content"/>
    </article>
  </article>
</my-other-post>
```

it is rendered as:
```html
<div is="my-other-post" data-riot-component="" title="What a great title">
    <span slot="summary">
        My beautiful post is just awesome
    </span>
    <p slot="content">
        And the next paragraph describes just how awesome it is
    </p>
    <article>
        <h1>What a great title</h1>
        <h2></h2>
        <article></article>
    </article>
</div>
```

and not as it is on the documentation:
```html
<my-other-post>
  <article>
    <h1>What a great title</h1>
    <h2><span>My beautiful post is just awesome</span></h2>
    <article>
      <p>
        And the next paragraph describes just how awesome it is
      </p>
    </article>
  </article>
</my-other-post>
```

I tried to use the components on the index.html using the ```tag``` instead of the ```div```definition but the result is the same and can not understand what possible I am doing wrong or if I am missing any step or configuration.

I am on the middle of a project and I need to use slots to organise the html code to hide the html complex structure when editing the content. I find Riot a good solution if I can put the slots working.

Can you please help to understand what might be wrong?
Is there a working example with ```slots``` and ```named slots```using webpack?

Thank you

**Comment by GianlucaGuarini** [comment]
You are probably on the wrong repo since this issue is not SSR related: that's the right one https://github.com/riot/riot

@bluellyr slots work as expected https://plnkr.co/edit/h6PucrbygBegSgTN 

If you try to use slots on your plain HTML files they will not work as informed here https://riot.js.org/documentation/#slots:

![Screen Shot 2022-04-25 at 11 41 21](https://user-images.githubusercontent.com/879612/165063776-6cc3fe22-4c20-493e-a392-0883e8ea3151.png)

There is an open discussion here https://github.com/riot/riot/discussions/2917 where we plan to improve this behavior but so far I didn't work on it yet. 

Thank you and have fun with your Riot.js project

**Comment by bluellyr** [comment]
Hi @GianlucaGuarini ,
thank you for your reply.

Yes I have just notice that I posted on the wrong repo, I am sorry for that.

I will check the links.

All the best
