### ISSUE TITLE
[feature] add ext option

### ISSUE THREAD

**Issue by SassNinja** [riot/ssr#4]
I'm setting up SSR for riot v4 and would like to keep the file extension `.tag`
However when requiring such files it doesn't work whereas `.riot` works.

I think the problem is the register module doesn't provide an option to specify a custom file extension.

@GianlucaGuarini can this be added?

**Comment by GianlucaGuarini** [comment]
Sure please make a PR adding the options object [here](https://github.com/riot/ssr/blob/master/src/register.js#L6)

I think it might look something like:
```js
register({ ext: '.tag' })
```

**Comment by SassNinja** [comment]
Alright, I've submitted a PR and added a test as well!
